### ISSUE TITLE
Set Up Class Diagram

### ISSUE THREAD

**Issue by h-nny** [bahnsm/IT4045C-Group-3-Project#4]
Set Up Class diagram and give descriptions to show the basic functionality of how our project will work

**Comment by h-nny** [comment]
One or two lines for each class to describe  use of interfaces, JME classes, Dalvik (Android) classes and resources, interfaces, etc.  Don't worry about putting more than a few words to each class; this does not need to be thorough.

**Comment by thoma4kw** [comment]
[Class DIagram.pdf](https://github.com/bahnsm/IT4045C-Group-3-Project/files/11648216/Class.DIagram.pdf)
