### ISSUE TITLE
Familiarize with Spotify API

### ISSUE THREAD

**Issue by gasawase** [bahnsm/IT4045C-Group-3-Project#7]

**Comment by gasawase** [comment]
Understand authorization and pre-auth, learn how to gather song information (currently playing, album name, track name, artist name, etc.), figure out how to (get the syntax for) controlling the currently playing song

**Comment by gasawase** [comment]
Categories to focus on: Access Token, API calls, Authorization, Tutorials>Client Credentials, Reference>Player,

**Comment by h-nny** [comment]
project shifted to another project
